# Generated by Django 2.2.6 on 2019-11-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemTitle', models.CharField(max_length=250)),
                ('itemURL', models.URLField(max_length=250)),
                ('itemDescription', models.TextField()),
                ('itemIngredients', models.TextField()),
            ],
        ),
    ]
