# Generated by Django 2.2.6 on 2019-11-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
